- hosts: all
  tasks:
    - name: ensure that nginx service is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started